apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata: 
  name: olavokruel-com-tls
spec:
  secretName: olavokruel-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: olavokruel.com
  dnsNames:
    - olavokruel.com
    - www.olavokruel.com
    acme:
      config: 
        - http01:
            ingressClass: nginx
          domains:
            - olavokruel.com
            - www.olavokruel.com